// LedgerLite — fictional mid-size SaaS (invoicing/accounting), EU + India
// customers, one AWS account. Illustrates the "paste your fleet, get a
// report" medium-business flow, including a genuine shift-in-time case.
export default {
  id: 'ledgerlite',
  name: 'LedgerLite',
  tagline: 'Mid-size invoicing SaaS — EU & India customers, single AWS account',
  maxInrPerTonne: 12000,
  workloads: [
    {
      name: 'Invoicing API (EU customers)',
      description: 'Core product API for EU tenants',
      kind: 'customer-facing',
      dataClass: 'personal_eu',
      latencySlaMs: 120,
      currentRegion: 'eu-west-1 (Ireland)',
      vcpus: 20,
      hoursPerMonth: 730,
      dataOutGbPerMonth: 80,
    },
    {
      name: 'Invoicing API (India customers)',
      description: 'Core product API for India tenants',
      kind: 'customer-facing',
      dataClass: 'personal_india',
      latencySlaMs: 100,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 12,
      hoursPerMonth: 730,
      dataOutGbPerMonth: 40,
    },
    {
      name: 'PDF Report Generation',
      description: 'Anonymised invoice-template rendering, deferrable overnight',
      kind: 'deferrable',
      dataClass: 'anonymised',
      jurisdiction: 'global_unconstrained',
      latencySlaMs: 5000,
      currentRegion: 'eu-west-1 (Ireland)',
      vcpus: 8,
      hoursPerMonth: 150,
      dataOutGbPerMonth: 20,
      deadlineFlexHours: 6,
    },
    {
      name: 'Nightly Reconciliation Batch',
      description: 'Already in Sweden — a good time-shift candidate, not a region-move one',
      kind: 'deferrable',
      dataClass: 'anonymised',
      jurisdiction: 'global_unconstrained',
      latencySlaMs: 5000,
      currentRegion: 'eu-north-1 (Sweden)',
      vcpus: 16,
      hoursPerMonth: 100,
      dataOutGbPerMonth: 10,
      deadlineFlexHours: 8,
    },
    {
      name: 'Customer Support Search Index',
      description: 'Anonymised support-ticket search, needs APAC-ish latency',
      kind: 'batch',
      dataClass: 'anonymised',
      jurisdiction: 'apac_sovereign',
      latencySlaMs: 250,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 10,
      hoursPerMonth: 400,
      dataOutGbPerMonth: 30,
    },
    {
      name: 'CI/CD Pipelines',
      description: 'Build and test runners',
      kind: 'batch',
      dataClass: 'public',
      jurisdiction: 'global_unconstrained',
      latencySlaMs: 5000,
      currentRegion: 'eu-west-1 (Ireland)',
      vcpus: 6,
      hoursPerMonth: 150,
      dataOutGbPerMonth: 10,
    },
  ],
};
