// QuickBite — fictional food-delivery company (Zomato-shaped), India-based.
// Illustrates: strict never-move for anything customer-facing or holding
// personal data, and genuine movement/shift opportunities for the batch and
// ML side of the business.
export default {
  id: 'quickbite',
  name: 'QuickBite',
  tagline: 'Food delivery — India-based, 12M orders/month',
  maxInrPerTonne: 15000,
  workloads: [
    {
      name: 'Order & Dispatch API',
      description: 'Places orders, matches riders in real time',
      kind: 'customer-facing',
      dataClass: 'personal_india',
      latencySlaMs: 50,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 64,
      hoursPerMonth: 730,
      dataOutGbPerMonth: 500,
    },
    {
      name: 'Rider Live Tracking',
      description: 'Streams rider GPS location to the customer app',
      kind: 'customer-facing',
      dataClass: 'personal_india',
      latencySlaMs: 80,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 32,
      hoursPerMonth: 730,
      dataOutGbPerMonth: 300,
    },
    {
      name: 'Payments Gateway',
      description: 'Card and UPI transaction processing',
      kind: 'customer-facing',
      dataClass: 'personal_india',
      latencySlaMs: 60,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 16,
      hoursPerMonth: 730,
      dataOutGbPerMonth: 50,
    },
    {
      name: 'Menu & Image Processing',
      description: 'Thumbnailing and tagging restaurant menu photos, no customer data',
      kind: 'batch',
      dataClass: 'anonymised',
      jurisdiction: 'apac_sovereign',
      latencySlaMs: 400,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 24,
      hoursPerMonth: 400,
      dataOutGbPerMonth: 150,
    },
    {
      name: 'Recommendation Model Training',
      description: 'Nightly retrain on anonymised order history',
      kind: 'deferrable',
      dataClass: 'anonymised',
      jurisdiction: 'global_unconstrained',
      latencySlaMs: 5000,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 128,
      hoursPerMonth: 200,
      dataOutGbPerMonth: 40,
      deadlineFlexHours: 10,
    },
    {
      name: 'Analytics ETL',
      description: 'Aggregated ordering/demand analytics, no personal fields',
      kind: 'deferrable',
      dataClass: 'anonymised',
      jurisdiction: 'global_unconstrained',
      latencySlaMs: 5000,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 48,
      hoursPerMonth: 300,
      dataOutGbPerMonth: 120,
      deadlineFlexHours: 8,
    },
    {
      name: 'Log Archive & Compaction',
      description: 'Long-term storage of application logs',
      kind: 'batch',
      dataClass: 'anonymised',
      jurisdiction: 'global_unconstrained',
      latencySlaMs: 5000,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 8,
      hoursPerMonth: 720,
      dataOutGbPerMonth: 3000,
    },
    {
      name: 'CI/CD Build Runners',
      description: 'Engineering build and test pipelines',
      kind: 'batch',
      dataClass: 'public',
      jurisdiction: 'apac_sovereign',
      latencySlaMs: 400,
      currentRegion: 'ap-south-1 (Mumbai)',
      vcpus: 16,
      hoursPerMonth: 200,
      dataOutGbPerMonth: 15,
    },
  ],
};
