"""
Ground-Truth Forecast Verification & Realized Savings Tracker
Records forward forecasts (1h, 3h, 6h, 12h) generated by ARIMA and LSTM,
and reconciles them against real observed carbon intensities once the elapsed
time window has passed.
Outputs verified evaluation metrics into data/forecast_verification.jsonl.
"""
import datetime
import json
import os
import sys
from typing import Dict, List, Optional

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from services.failsafe_engine import failsafe_engine

PENDING_FILE = os.path.join(config.DATA_DIR, "pending_forecasts.json")
VERIFICATION_LOG = os.path.join(config.DATA_DIR, "forecast_verification.jsonl")


def load_pending() -> List[Dict]:
    if os.path.exists(PENDING_FILE):
        try:
            with open(PENDING_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return []


def save_pending(pending_list: List[Dict]):
    try:
        with open(PENDING_FILE, "w") as f:
            json.dump(pending_list, f, indent=2)
    except Exception as e:
        print(f"Error saving pending forecasts: {e}")


def record_cycle_forecasts(
    profile: str,
    model_name: str,
    origin_dt_utc: datetime.datetime,
    region_forecasts: Dict[str, Dict],
    horizons: List[int] = [1, 3, 6, 12]
):
    """
    Saves forward forecast checkpoints at 1h, 3h, 6h for future ground-truth reconciliation.
    """
    pending = load_pending()
    origin_iso = origin_dt_utc.isoformat()

    for region_name, rdata in region_forecasts.items():
        cur_ci = float(rdata.get("current_ci", 250.0))
        series = rdata.get("forecast_12h") or rdata.get("forecast_series") or []
        if not series:
            continue

        for h in horizons:
            if len(series) >= h:
                target_dt = origin_dt_utc + datetime.timedelta(hours=h)
                pred_ci_at_h = float(series[h - 1])
                
                # Check optimal decision within the h window
                sub_series = series[:h]
                min_idx = min(range(len(sub_series)), key=lambda i: sub_series[i])
                opt_ci_in_window = float(sub_series[min_idx])
                opt_offset = min_idx + 1 if opt_ci_in_window < cur_ci else 0

                entry = {
                    "id": f"{profile}_{region_name}_{origin_iso}_{h}h",
                    "profile": profile,
                    "model_name": model_name,
                    "region_name": region_name,
                    "origin_timestamp_utc": origin_iso,
                    "target_timestamp_utc": target_dt.isoformat(),
                    "horizon_hours": h,
                    "origin_ci": cur_ci,
                    "predicted_point_ci": pred_ci_at_h,
                    "predicted_optimal_offset": opt_offset,
                    "predicted_optimal_ci": opt_ci_in_window if opt_offset > 0 else cur_ci,
                    "expected_savings_pct": round(max(0.0, (cur_ci - opt_ci_in_window) / max(1.0, cur_ci) * 100), 2)
                }
                pending.append(entry)

    save_pending(pending)


def reconcile_with_live_data(
    live_ci_map: Dict[str, float],
    now_dt_utc: Optional[datetime.datetime] = None
) -> List[Dict]:
    """
    Finds pending forecasts whose target time has arrived, evaluates prediction error
    and realized carbon reduction, and logs to forecast_verification.jsonl.
    """
    if now_dt_utc is None:
        now_dt_utc = datetime.datetime.now(datetime.timezone.utc)

    pending = load_pending()
    if not pending:
        return []

    remaining_pending = []
    verified_entries = []

    for entry in pending:
        target_iso = entry["target_timestamp_utc"]
        try:
            target_dt = datetime.datetime.fromisoformat(target_iso)
            if target_dt.tzinfo is None:
                target_dt = target_dt.replace(tzinfo=datetime.timezone.utc)
        except Exception:
            continue

        # If time has arrived or passed (allow within 15 min window)
        if now_dt_utc >= target_dt:
            region = entry["region_name"]
            actual_ci = live_ci_map.get(region)

            if actual_ci is not None:
                actual_ci = float(failsafe_engine.clamp_ci(actual_ci))
                pred_ci = float(entry["predicted_point_ci"])
                orig_ci = float(entry["origin_ci"])
                abs_err = abs(pred_ci - actual_ci)
                sq_err = (pred_ci - actual_ci) ** 2

                # Did the grid actually get cleaner?
                actual_change = actual_ci - orig_ci
                pred_change = pred_ci - orig_ci
                directional_correct = (actual_change * pred_change) >= 0

                # Realized savings if delayed
                actual_savings_pct = round(((orig_ci - actual_ci) / max(1.0, orig_ci)) * 100, 2)
                regret = (entry["predicted_optimal_offset"] > 0 and actual_savings_pct < 0)

                verified_record = {
                    "verified_at_utc": now_dt_utc.isoformat(),
                    "origin_timestamp_utc": entry["origin_timestamp_utc"],
                    "target_timestamp_utc": target_iso,
                    "profile": entry["profile"],
                    "model_name": entry["model_name"],
                    "region_name": region,
                    "horizon_hours": entry["horizon_hours"],
                    "origin_ci": orig_ci,
                    "predicted_ci": pred_ci,
                    "actual_ci": actual_ci,
                    "absolute_error": round(abs_err, 2),
                    "squared_error": round(sq_err, 2),
                    "directional_correct": directional_correct,
                    "expected_savings_pct": entry["expected_savings_pct"],
                    "actual_savings_pct": actual_savings_pct,
                    "regret_occurred": regret
                }

                failsafe_engine.atomic_append_jsonl(VERIFICATION_LOG, verified_record)
                verified_entries.append(verified_record)
            else:
                # Keep if live CI was temporarily unavailable
                remaining_pending.append(entry)
        else:
            remaining_pending.append(entry)

    save_pending(remaining_pending)
    if verified_entries:
        print(f"  Reconciled {len(verified_entries)} ground-truth forecast records -> {VERIFICATION_LOG}")
    return verified_entries


def compute_verification_metrics() -> Dict:
    """
    Computes summary MAE, RMSE, Directional Accuracy, and Realized Carbon Savings
    by horizon (1h, 3h, 6h, 12h) and model.
    """
    if not os.path.exists(VERIFICATION_LOG):
        return {}

    records_by_group = {}
    try:
        with open(VERIFICATION_LOG, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Skip any malformed or older-schema record instead of letting one
                # bad line collapse the whole summary to {}.
                try:
                    r = json.loads(line)
                except Exception:
                    continue
                model = r.get("model_name") or r.get("profile")
                horizon = r.get("horizon_hours")
                if model is None or horizon is None or "absolute_error" not in r:
                    continue
                records_by_group.setdefault((model, horizon), []).append(r)
    except Exception:
        return {}

    summary = {}
    for (model, h), records in records_by_group.items():
        n = len(records)
        if n == 0:
            continue
        mae = sum(r.get("absolute_error", 0.0) for r in records) / n
        rmse = (sum(r.get("squared_error", 0.0) for r in records) / n) ** 0.5
        dir_acc = (sum(1 for r in records if r.get("directional_correct")) / n) * 100
        avg_savings = sum(r.get("actual_savings_pct", 0.0) for r in records) / n
        regret_rate = (sum(1 for r in records if r.get("regret_occurred")) / n) * 100

        summary.setdefault(model, {})[f"{h}h"] = {
            "sample_count": n,
            "mae_gco2": round(mae, 2),
            "rmse_gco2": round(rmse, 2),
            "directional_accuracy_pct": round(dir_acc, 1),
            "mean_realized_savings_pct": round(avg_savings, 2),
            "regret_rate_pct": round(regret_rate, 1)
        }

    return summary
